class EventType:
    N14E_ARRIVAL = 1
    N14E_GO_ACROSS = 2
    N14E_TURN_LEFT = 3

    S14E_ARRIVAL = 4
    S14E_GO_ACROSS = 5 
    S14E_TURN_RIGHT = 6
    
    EN14W_ARRIVAL = 7
    EN14W_GO_ACROSS = 8
    EN14W_TURN_RIGHT = 9

    ES14W_ARRIVAL = 10
    ES14W_GO_ACROSS = 11
    ES14W_TURN_LEFT = 12
    
    N_ATLANTIC_S_ARRIVAL = 13
    N_ATLANTIC_S_GO_ACROSS = 14
    N_ATLANTIC_S_TURN_LEFT = 15
    N_ATLANTIC_S_TURN_RIGHT = 16
    
    S_ATLANTIC_N_ARRIVAL = 17
    S_ATLANTIC_N_GO_ACROSS = 18
    S_ATLANTIC_N_TURN_LEFT = 19
    S_ATLANTIC_N_TURN_RIGHT = 20

    N14E_ARRIVAL_TL = 21
    N14E_GO_ACROSS_TL = 22
    N14E_TURN_LEFT_TL = 23

    S14E_ARRIVAL_TL = 24
    S14E_GO_ACROSS_TL = 25 
    S14E_TURN_RIGHT_TL = 26
    
    EN14W_ARRIVAL_TL = 27
    EN14W_GO_ACROSS_TL = 28
    EN14W_TURN_RIGHT_TL = 29

    ES14W_ARRIVAL_TL = 30
    ES14W_GO_ACROSS_TL = 31
    ES14W_TURN_LEFT_TL = 32
    
    N_ATLANTIC_S_ARRIVAL_TL = 33
    N_ATLANTIC_S_GO_ACROSS_TL = 34
    N_ATLANTIC_S_TURN_LEFT_TL = 35
    N_ATLANTIC_S_TURN_RIGHT_TL = 36
    
    S_ATLANTIC_N_ARRIVAL_TL = 37
    S_ATLANTIC_N_GO_ACROSS_TL = 38
    S_ATLANTIC_N_TURN_LEFT_TL = 39
    S_ATLANTIC_N_TURN_RIGHT_TL = 40

    _14_LIGHT_TURNS_GREEN = 41
    _14_LIGHT_TURNS_RED = 42

# print EventType.ARRIVAL